In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
ds_train = pd.read_csv('Google_Stock_Price_Train.csv')
training_set = ds_train.iloc[:,1:2].values

In [20]:
print(training_set)

[[325.25]
 [331.27]
 [329.83]
 ...
 [793.7 ]
 [783.33]
 [782.75]]


In [21]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
training_set_scaled = sc.fit_transform(training_set)

In [34]:
x_train = []
y_train = []
for i in range(60,1258):
    x_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i,0])
x_train, y_train = np.array(x_train), np.array(y_train)

In [35]:
print(x_train)

[[0.08581368 0.09701243 0.09433366 ... 0.07846566 0.08034452 0.08497656]
 [0.09701243 0.09433366 0.09156187 ... 0.08034452 0.08497656 0.08627874]
 [0.09433366 0.09156187 0.07984225 ... 0.08497656 0.08627874 0.08471612]
 ...
 [0.92106928 0.92438053 0.93048218 ... 0.95475854 0.95204256 0.95163331]
 [0.92438053 0.93048218 0.9299055  ... 0.95204256 0.95163331 0.95725128]
 [0.93048218 0.9299055  0.93113327 ... 0.95163331 0.95725128 0.93796041]]


In [36]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [37]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [38]:
regressor = Sequential()

In [39]:
regressor.add(LSTM(units= 50, return_sequences= True, input_shape = (x_train.shape[1],1)))
regressor.add(Dropout(0.2))

In [40]:
regressor.add(LSTM(units= 50, return_sequences= True))
regressor.add(Dropout(0.2))

In [41]:
regressor.add(LSTM(units= 50, return_sequences= True))
regressor.add(Dropout(0.2))

In [42]:
regressor.add(LSTM(units= 50))
regressor.add(Dropout(0.2)) 

In [43]:
regressor.add(Dense(units = 1))

In [44]:
regressor.compile(optimizer= 'adam', loss= 'mean_squared_error')

In [ ]:
regressor.fit(x_train, y_train, epochs= 100, batch_size = 32)

Epoch 1/100
38/38 [==============================] - 14s 120ms/step - loss: 0.0419
Epoch 2/100
38/38 [==============================] - 5s 122ms/step - loss: 0.0065
Epoch 3/100
38/38 [==============================] - 4s 115ms/step - loss: 0.0054
Epoch 4/100
38/38 [==============================] - 4s 116ms/step - loss: 0.0046
Epoch 5/100
38/38 [==============================] - 4s 116ms/step - loss: 0.0051
Epoch 6/100
38/38 [==============================] - 4s 115ms/step - loss: 0.0053
Epoch 7/100
38/38 [==============================] - 4s 115ms/step - loss: 0.0040
Epoch 8/100
38/38 [==============================] - 5s 119ms/step - loss: 0.0047
Epoch 9/100
38/38 [==============================] - 5s 124ms/step - loss: 0.0052
Epoch 10/100
38/38 [==============================] - 5s 120ms/step - loss: 0.0044
Epoch 11/100
38/38 [==============================] - 4s 115ms/step - loss: 0.0041
Epoch 12/100
38/38 [==============================] - 4s 117ms/step - loss: 0.0042
Epoch 13/100